[Interface]
PrivateKey = cF7N1kKJmGkVxgXrJmVdWNyBXhxPWXnXJmVdWNyBXhw=
Address = 10.0.0.3/24
DNS = 8.8.8.8, 1.1.1.1
MTU = 1420

[Peer]
PublicKey = KJ7JfsOdUn6OVpKqWboWXOzCYiyQXYoYKnWeXOzCYiw=
AllowedIPs = 0.0.0.0/0
Endpoint = vpn-africell-01.ao:51820
PersistentKeepalive = 25
