[Interface]
PrivateKey = YF8O2lLKlGlVxgXrJmVdWNyBXhxPWXnXJmVdWNyBXhw=
Address = 10.0.0.2/24
DNS = 8.8.8.8, 1.1.1.1
MTU = 1420

[Peer]
PublicKey = JI6IerNcTm5NUvJoanpVWNyBXhxPWXnXJmVdWNyBXhw=
AllowedIPs = 0.0.0.0/0
Endpoint = vpn-unitel.ao:51820
PersistentKeepalive = 25
